version: '3.8'
services:
  app:
    container_name: whitepages
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3030:3030"
    restart: unless-stopped
